<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="10" passed="5" failed="5" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-09-22T13:07:50 IST" name="Default suite" finished-at="2022-09-22T13:08:26 IST" duration-ms="35639">
    <groups>
    </groups>
    <test started-at="2022-09-22T13:07:50 IST" name="Default test" finished-at="2022-09-22T13:08:26 IST" duration-ms="35639">
      <class name="mobile.login">
        <test-method is-config="true" signature="launchapp()[pri:0, instance:mobile.login@2b91004a]" started-at="2022-09-22T13:07:50 IST" name="launchapp" finished-at="2022-09-22T13:07:54 IST" duration-ms="4325" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchapp -->
        <test-method signature="login_invalid_password()[pri:0, instance:mobile.login@2b91004a]" started-at="2022-09-22T13:07:54 IST" name="login_invalid_password" finished-at="2022-09-22T13:07:55 IST" duration-ms="477" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [error message should be displayed] but found [a1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [error message should be displayed] but found [a1]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at mobile.login.login_invalid_password(login.java:71)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_invalid_password -->
        <test-method is-config="true" signature="launchapp()[pri:0, instance:mobile.login@2b91004a]" started-at="2022-09-22T13:07:55 IST" name="launchapp" finished-at="2022-09-22T13:07:57 IST" duration-ms="2259" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchapp -->
        <test-method signature="login_password_empty()[pri:0, instance:mobile.login@2b91004a]" started-at="2022-09-22T13:07:57 IST" name="login_password_empty" finished-at="2022-09-22T13:07:58 IST" duration-ms="453" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [error message should be displayed] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [error message should be displayed] but found []
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at mobile.login.login_password_empty(login.java:83)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_password_empty -->
        <test-method is-config="true" signature="launchapp()[pri:0, instance:mobile.login@2b91004a]" started-at="2022-09-22T13:07:58 IST" name="launchapp" finished-at="2022-09-22T13:08:01 IST" duration-ms="2826" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchapp -->
        <test-method signature="login_valid_password(java.lang.String,java.lang.String)[pri:0, instance:mobile.login@2b91004a]" started-at="2022-09-22T13:08:01 IST" name="login_valid_password" data-provider="login_data_password" finished-at="2022-09-22T13:08:01 IST" duration-ms="749" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[aja]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[abcdef@123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_valid_password -->
        <test-method is-config="true" signature="launchapp()[pri:0, instance:mobile.login@2b91004a]" started-at="2022-09-22T13:08:01 IST" name="launchapp" finished-at="2022-09-22T13:08:05 IST" duration-ms="3375" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchapp -->
        <test-method signature="login_valid_username(java.lang.String,java.lang.String)[pri:0, instance:mobile.login@2b91004a]" started-at="2022-09-22T13:08:05 IST" name="login_valid_username" data-provider="login_data_username" finished-at="2022-09-22T13:08:05 IST" duration-ms="720" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[aja]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[abc]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_valid_username -->
        <test-method is-config="true" signature="launchapp()[pri:0, instance:mobile.login@2b91004a]" started-at="2022-09-22T13:08:05 IST" name="launchapp" finished-at="2022-09-22T13:08:08 IST" duration-ms="2275" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchapp -->
        <test-method signature="login_valid_username(java.lang.String,java.lang.String)[pri:0, instance:mobile.login@2b91004a]" started-at="2022-09-22T13:08:08 IST" name="login_valid_username" data-provider="login_data_username" finished-at="2022-09-22T13:08:08 IST" duration-ms="729" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[qwertyuiopqwertyuiop]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[abc]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_valid_username -->
        <test-method is-config="true" signature="launchapp()[pri:0, instance:mobile.login@2b91004a]" started-at="2022-09-22T13:08:08 IST" name="launchapp" finished-at="2022-09-22T13:08:11 IST" duration-ms="2889" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchapp -->
        <test-method signature="login_valid_username(java.lang.String,java.lang.String)[pri:0, instance:mobile.login@2b91004a]" started-at="2022-09-22T13:08:11 IST" name="login_valid_username" data-provider="login_data_username" finished-at="2022-09-22T13:08:12 IST" duration-ms="683" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[abc123]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[abc]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_valid_username -->
        <test-method is-config="true" signature="launchapp()[pri:0, instance:mobile.login@2b91004a]" started-at="2022-09-22T13:08:12 IST" name="launchapp" finished-at="2022-09-22T13:08:15 IST" duration-ms="2745" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchapp -->
        <test-method signature="loginintegration(java.lang.String,java.lang.String)[pri:0, instance:mobile.login@2b91004a]" started-at="2022-09-22T13:08:15 IST" name="loginintegration" data-provider="login_data_ntegration" finished-at="2022-09-22T13:08:15 IST" duration-ms="785" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[aja]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[abcdef@123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginintegration -->
        <test-method is-config="true" signature="launchapp()[pri:0, instance:mobile.login@2b91004a]" started-at="2022-09-22T13:08:15 IST" name="launchapp" finished-at="2022-09-22T13:08:18 IST" duration-ms="2873" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchapp -->
        <test-method signature="username_empty()[pri:0, instance:mobile.login@2b91004a]" started-at="2022-09-22T13:08:18 IST" name="username_empty" finished-at="2022-09-22T13:08:19 IST" duration-ms="468" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [error message should be displayed] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [error message should be displayed] but found []
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at mobile.login.username_empty(login.java:50)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- username_empty -->
        <test-method is-config="true" signature="launchapp()[pri:0, instance:mobile.login@2b91004a]" started-at="2022-09-22T13:08:19 IST" name="launchapp" finished-at="2022-09-22T13:08:22 IST" duration-ms="2768" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchapp -->
        <test-method signature="username_less_than_3()[pri:0, instance:mobile.login@2b91004a]" started-at="2022-09-22T13:08:22 IST" name="username_less_than_3" finished-at="2022-09-22T13:08:22 IST" duration-ms="597" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [error message should be displayed] but found [aa]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [error message should be displayed] but found [aa]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at mobile.login.username_less_than_3(login.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- username_less_than_3 -->
        <test-method is-config="true" signature="launchapp()[pri:0, instance:mobile.login@2b91004a]" started-at="2022-09-22T13:08:22 IST" name="launchapp" finished-at="2022-09-22T13:08:25 IST" duration-ms="2979" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchapp -->
        <test-method signature="username_more_than_20()[pri:0, instance:mobile.login@2b91004a]" started-at="2022-09-22T13:08:25 IST" name="username_more_than_20" finished-at="2022-09-22T13:08:26 IST" duration-ms="589" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [error message should be displayed] but found [qwertyuiopasdqwertyuiopasd]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [error message should be displayed] but found [qwertyuiopasdqwertyuiopasd]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at mobile.login.username_more_than_20(login.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- username_more_than_20 -->
      </class> <!-- mobile.login -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
